core/genesis.go, core/vm/contracts.go, core/vm/ipgraph.go
Enhance the IP Graph and add support Royalty LRP policy.
Move the IP Graph precompile address to 0x0101
Tested on the Odyssey devnet.
=> Add support of royalty LRP 

params/version.go
finalizes the story execution client v0.10.0 release version
fixes: none
=> chore(release): finalize story-geth v0.10.0 stable release

cmd/devp2p/internal/ethtest/testdata/genesis.json, cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, core/genesis.go, core/state_processor_test.go, core/txpool/validation.go, core/types/transaction_signing.go, eth/api_backend.go, eth/backend.go, eth/ethconfig/config.go, eth/tracers/internal/tracetest/testdata/call_tracer/blob_tx.json, eth/tracers/internal/tracetest/testdata/prestate_tracer/blob_tx.json, params/config.go, tests/init.go
makes 4844 an opt-in feature that is default disabled
=> chore(core): disable 4844 support by default

params/version.go
bump story-geth to v0.10.1 stable release
=> chore(release): finalize geth v0.10.1 stable release

params/version.go
finalizes the upcoming public odyssey client v0.10.0 release
=> chore(release): finalize odyssey client v0.10.0 stable release

params/version.go
begin v0.10.1 unstable release
issue: none
=> chore(release): begin v0.10.1 unstable release

cmd/utils/flags.go
bake in minimum base gas price as 16 gwei
issue: #57
=> fix(ethconfig): bake in minimum base gas price

params/version.go
finalize story-geth 0.10.1 stable release
close: none
=> chore(release): finalize story-geth 0.10.1 stable release

params/version.go
begin v0.10.2 unstable release
close: none
=> chore(release): begin v0.10.2 unstable release

core/vm/ipgraph.go
Closes https://github.com/piplabs/trust-story/issues/30
=> fix(ipgraph): add parent ip calculate gas cost based on parents count

.github/CODEOWNERS
Add more code owners
issue: none
=> chore(codeowner): update code owner

cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, core/genesis.go, eth/backend.go, eth/ethconfig/config.go
add OverrideStoryDenomTheogony override option
close: none
=> feat(cmd): add OverrideStoryDenomTheogony override option

params/version.go
finalize story-geth 0.11.0 stable release
close: none
=> chore(release): finalize story-geth 0.11.0 stable release

core/vm/ipgraph.go
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/7
=> fix(ipgraph): check royalty percentage not exceeds uint32 range

core/vm/ipgraph.go
Precisely check the ipgraph function input.
Closes https://github.com/piplabs/trust-story/issues/6
=> fix(ipgraph): precisely check the input length

core/vm/ipgraph.go
Donot allow invokie ipgraph through DELEGATECALL type
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/8
=> fix(ipgraph): disable to make delegatecall to ipgraph

cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, consensus/misc/eip1559/eip1559.go, core/genesis.go, core/vm/contracts.go, core/vm/evm.go, core/vm/ipgraph.go, eth/backend.go, eth/ethconfig/config.go, params/config.go, params/protocol_params.go, params/story_params.go
Removed Theogony related codes. We can also override eip1559 denominator with `--override.storydenom` flag.
related PRs:
- https://github.com/piplabs/story-geth/pull/64
- https://github.com/piplabs/story-geth/pull/65
- https://github.com/piplabs/story-geth/pull/68
=> feat(*): remove theogony

params/bootnodes.go
update bootnode configs for testing
issue: none
=> chore(*): update bootnode configs

params/config.go
Update genesis alloc data and corresponding hash for story. 
This includes the latest change of contracts.
=> chore(*): update genesis alloc data for story

core/vm/ipgraph.go
Update ipgraph acl address which deployed with pre-deployed CREATE3 deployer
=> chore(ipgraph): update ipgraph acl address

cmd/utils/flags.go
update story configs
issue: none
=> chore(config): update story configs

core/vm/contracts_test.go
This is the PR for testing this issue: https://github.com/piplabs/trust-story/issues/30
It tests the following scenarios:
- Single parent
- Three parents
- Zero parents
- Large number (100) of parents
The test verifies that the gas cost now correctly scales with the number of parents.
=> Testing IP Graph precompile approximation of required gas 

cmd/utils/flags.go, core/genesis.go, params/bootnodes.go, params/config.go, params/story_params.go
Rename homer network to aeneid network
=> chore(netconf): rename homer to aeneid

params/version.go
begin story-geth 1.0.1 unstable release
close: none
=> chore(release): begin story-geth 1.0.1 unstable release

params/version.go
finalize story-geth 1.0.1 stable release
close: none
=> chore(release): finalize story-geth 1.0.1 stable release

.github/CODEOWNERS
=> chore(*): update codeowner

params/version.go
begin story-geth 1.0.2 unstable release
issue: none
=> chore(release): begin story-geth 1.0.2 unstable release

params/version.go
finalize story-geth 1.0.2 stable release
issue: none
=> chore(release): finalize story-geth 1.0.2 stable release

.github/workflows/build-release-artifacts.yml
chore(ci): change workflow runner version
=> chore(ci): change workflow runner version

params/version.go
begin story-geth 1.0.3 unstable release
issue: none
=> chore(release): begin story-geth 1.0.3 unstable release

README.md
add build instruction
issue: none
=> chore(readme): add build instruction

.github/workflows/notify-slack-on-pr-merge.yml
add qa messenger notfication
issue: none
=> feat(ci): add qa messenger notification once a pr merged

params/config.go
Updated genesis.json file for local devnet according to the latest updates in https://github.com/piplabs/story/pull/499.
=> chore(genesis): update genesis staking precompile

version/version.go
finalize story-geth 1.1.0 stable release
close: none
=> chore(release): finalize story-geth 1.1.0 stable release

core/vm/ipgraph.go, params/config.go
=> params: add prague timestamp for Story Mainnet

params/config.go
=> params: update prague timestamp for Story Mainnet

version/version.go
finalize story 1.1.1 stable release
close: none
=> chore(release): finalize story 1.1.1 stable release

accounts/abi/bind/v2/lib.go, accounts/abi/bind/v2/lib_test.go
The root cause of the flaky test was a nonce conflict caused by async contract deployments.
This solution defines a custom deployer with automatic nonce management.
=> account/abi/bind/v2: fix TestDeploymentWithOverrides
