params/version.go
bumps the story geth client to 0.9.2 stable
=> chore(release): bump client to v0.9.2 stable

params/version.go
begins the new `story-geth` client 0.9.3 unstable release cycle
=> chore(release): begin 0.9.3 unstable release

.github/workflows/go.yml, params/config.go, tests/fuzzers/bls12381/precompile_fuzzer.go
**CONTEXT**
This is the original workflow from the upstream geth repo, but it never got triggered.
**PR Notes**
1. update checkout version tag
2. fix the branch mismatch
3. update arch type from i386 to amd64
4. use ubuntu-latest runner
5. add cache feature which greatly speed up the running of this workflow
=> [fix] go-testing workflow

.github/workflows/build-release-artifacts.yml
**CONTEXT**
It is essential to have a checksum for each binary available for public to download from security and best practices perspective.
**PR NOTES**
1. add checksum for reach binary built and push them to the release page
=> [feat] add checksum for each platform

.github/workflows/build-release-artifacts.yml
Updates the GH release workflow to support uploading of checksums, which is currently broken.
Fixes #35
=> bugfix(workflows): fix release checksum upload via file globs

params/version.go
begins the next story v0.10.1 execution client release cycle
fixes: none
=> chore(release): begin story-geth v0.10.1 unstable release

.github/workflows/ci-s3.yml
pins go version 1.22 to the s3 public binary upload to fix incompatibility issues
=> chore(workflow): pin go v1.22 to s3 upload workflow

core/vm/contracts.go
adjust release ordering so that precompiles are introduced from cancun and beyond
=> chore(core/vm): ensures precompiles originate from the cancun release

core/vm/contracts.go, core/vm/evm.go, core/vm/ipgraph.go
Based on #64. The base branch will be changed automatically to `main` when the PR is merged.
Added `ipgraphTheogony` precompiled contract for Theogony hardfork.
=> hardfork(ipgraph): add ipgraph precompile contract for theogony

core/vm/evm.go, core/vm/ipgraph.go
only allow using CALL opcode to call write functions of ip-graph "addParentIp()" and "setRoyalty()"
Closes https://github.com/FuzzingLabs/story-audit-monorepo/issues/9
=> fix(ipgraph): only allow using opcode call to invoke write functions

cmd/utils/flags.go, core/genesis.go, params/bootnodes.go, params/config.go
support `--story` flag for Story mainnet. Need to update the followings:
- genesisAllocData 
- genesis block hash
- boot nodes
=> feat(config): add story mainnet flag

README.md
README updated because we were still using the one in the original Ethereum Geth repo, and in the past it caused confusion with some partners.
=> Update README.md to Story-Geth 

README.md
Added a section introducing the Story-Localnet repository, which enables developers to run multiple Story nodes locally using Docker for easier testing and development.
=> chore(README.md): guide story-localnet

params/config.go
As seen [here](https://github.com/piplabs/story-geth/pull/94/files#diff-10ff00a15ef58da7485fedeca3906c73cb236fde4b143a9d61601c63cbf1ffe8R901), the Aeneid was not included in Story, so default value of EIP1559 denominator, 8, was used for Aeneid.
=> feat(params): use default denom for aeneid

cmd/utils/flags.go
Gas price determines the minimum priority fee that users need to pay. The higher minimum priority fee confuses users when they don't set a high enough priority fee. Adjust it back to default to be compatible with Ethereum toolings
=> feat(*): remove min priority fee restriction

core/vm/ipgraph.go
The PR is for preventing from potential int overflow in some situations.
=> fix(ipgraph): prevent overflow in calculating gas of add parent

core/vm/ipgraph.go
This PR add the ACL to hasAncestorIp() function.
=> fix(ipgraph): apply acl to function hasAncestorIp

README.md
- Update README cmd to Iliad
- Add story-geth mainnet example cmd
- Markdown linting
=> doc(readme): update to iliad, add cmd, markdown lint style

params/config.go
=> params: add prague timestamp for Story Aeneid testnet

.github/workflows/ci-s3.yml, core/blockchain_test.go, eth/protocols/eth/handler_test.go, params/bootnodes.go
1. Replace the domain name at the end of the enode URL with its corresponding IP address to avoid bootnode parsing failure.
2. Fix unit test failures caused by omitted execution requests and unsupported blob transactions.
3. Resolve workflow failures resulting from the updated path of version.go.
=> params: replace Aeneid bootnode config
